user-message: "This stack project is generated."

nix:
  packages: [cacert, git, hostname, z3]

resolver: lts-24.28

# We have 1 package.
packages:
  - ./.

extra-deps:
  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - liquid-prelude-0.9.10.1.2
  - liquid-vector-0.13.1.0.1
