[ { dep = "Diff", ver = "1.0.2" }
, { dep = "HUnit", ver = "1.6.2.0" }
, { dep = "OneTuple", ver = "0.4.2.1" }
, { dep = "QuickCheck", ver = "2.16.0.0" }
, { dep = "StateVar", ver = "1.2.2" }
, { dep = "aeson", ver = "2.2.3.0" }
, { dep = "ansi-terminal", ver = "1.1.5" }
, { dep = "ansi-terminal-types", ver = "1.1.3" }
, { dep = "ascii-progress", ver = "0.3.3.0" }
, { dep = "assoc", ver = "1.1.1" }
, { dep = "async", ver = "2.2.6" }
, { dep = "attoparsec", ver = "0.14.4" }
, { dep = "base-compat", ver = "0.15.0" }
, { dep = "base-orphans", ver = "0.9.4" }
, { dep = "base64-bytestring", ver = "1.2.1.0" }
, { dep = "bifunctors", ver = "5.6.3" }
, { dep = "bitvec", ver = "1.1.5.0" }
, { dep = "boxes", ver = "0.1.5" }
, { dep = "call-stack", ver = "0.4.0" }
, { dep = "case-insensitive", ver = "1.2.1.0" }
, { dep = "cereal", ver = "0.5.8.3" }
, { dep = "character-ps", ver = "0.1" }
, { dep = "clock", ver = "0.8.4" }
, { dep = "cmdargs", ver = "0.10.22" }
, { dep = "colour", ver = "2.3.6" }
, { dep = "comonad", ver = "5.0.10" }
, { dep = "concurrent-output", ver = "1.10.21" }
, { dep = "contravariant", ver = "1.5.6" }
, { dep = "cryptohash-sha1", ver = "0.11.101.0" }
, { dep = "data-default", ver = "0.8.0.2" }
, { dep = "data-fix", ver = "0.3.4" }
, { dep = "distributive", ver = "0.6.3" }
, { dep = "dlist", ver = "1.0" }
, { dep = "extra", ver = "1.8.1" }
, { dep = "fgl", ver = "5.8.3.0" }
, { dep = "fingertree", ver = "0.1.6.3" }
, { dep = "free", ver = "5.2" }
, { dep = "generically", ver = "0.1.1" }
, { dep = "githash", ver = "0.1.7.0" }
, { dep = "gitrev", ver = "1.3.1" }
, { dep = "hashable", ver = "1.5.1.0" }
, { dep = "haskell-lexer", ver = "1.2.1" }
, { dep = "hscolour", ver = "1.25" }
, { dep = "hspec", ver = "2.11.16" }
, { dep = "hspec-core", ver = "2.11.16" }
, { dep = "hspec-discover", ver = "2.11.16" }
, { dep = "hspec-expectations", ver = "0.8.4" }
, { dep = "hspec-smallcheck", ver = "0.5.3" }
, { dep = "indexed-traversable", ver = "0.1.4" }
, { dep = "indexed-traversable-instances", ver = "0.1.2" }
, { dep = "integer-conversion", ver = "0.1.1" }
, { dep = "integer-logarithms", ver = "1.0.5" }
, { dep = "intern", ver = "0.9.6" }
, { dep = "lens-family", ver = "2.1.3" }
, { dep = "lens-family-core", ver = "2.1.3" }
, { dep = "lifted-base", ver = "0.2.3.12" }
, { dep = "logict", ver = "0.8.2.0" }
, { dep = "megaparsec", ver = "9.7.0" }
, { dep = "monad-control", ver = "1.0.3.1" }
, { dep = "monad-loops", ver = "0.4.3" }
, { dep = "mono-traversable", ver = "1.0.21.0" }
, { dep = "nats", ver = "1.1.2" }
, { dep = "network", ver = "3.2.8.0" }
, { dep = "network-uri", ver = "2.6.4.2" }
, { dep = "optparse-applicative", ver = "0.19.0.0" }
, { dep = "parser-combinators", ver = "1.3.1" }
, { dep = "prettyprinter", ver = "1.7.1" }
, { dep = "prettyprinter-ansi-terminal", ver = "1.1.3" }
, { dep = "primitive", ver = "0.9.1.0" }
, { dep = "profunctors", ver = "5.6.3" }
, { dep = "quickcheck-io", ver = "0.2.0" }
, { dep = "random", ver = "1.3.1" }
, { dep = "resourcet", ver = "1.3.0" }
, { dep = "rest-rewrite", ver = "0.4.5" }
, { dep = "safe", ver = "0.3.21" }
, { dep = "scientific", ver = "0.3.8.1" }
, { dep = "semialign", ver = "1.3.1" }
, { dep = "semigroupoids", ver = "6.0.2" }
, { dep = "smallcheck", ver = "1.2.1.1" }
, { dep = "smtlib-backends", ver = "0.4" }
, { dep = "smtlib-backends-process", ver = "0.3" }
, { dep = "split", ver = "0.2.5" }
, { dep = "splitmix", ver = "0.1.3.2" }
, { dep = "store", ver = "0.7.20" }
, { dep = "store-core", ver = "0.4.4.7" }
, { dep = "strict", ver = "0.5.1" }
, { dep = "syb", ver = "0.7.3" }
, { dep = "tagged", ver = "0.8.10" }
, { dep = "tasty", ver = "1.5.3" }
, { dep = "temporary", ver = "1.3" }
, { dep = "terminal-size", ver = "0.3.4" }
, { dep = "text-iso8601", ver = "0.1.1" }
, { dep = "text-short", ver = "0.1.6.1" }
, { dep = "th-abstraction", ver = "0.7.2.0" }
, { dep = "th-compat", ver = "0.1.7" }
, { dep = "th-expand-syns", ver = "0.4.12.0" }
, { dep = "th-lift", ver = "0.8.7" }
, { dep = "th-lift-instances", ver = "0.1.20" }
, { dep = "th-orphans", ver = "0.13.17" }
, { dep = "th-reify-many", ver = "0.1.10" }
, { dep = "th-utilities", ver = "0.2.5.2" }
, { dep = "these", ver = "1.2.1" }
, { dep = "time-compat", ver = "1.9.8" }
, { dep = "transformers-base", ver = "0.4.6" }
, { dep = "transformers-compat", ver = "0.7.2" }
, { dep = "unliftio-core", ver = "0.2.1.0" }
, { dep = "unordered-containers", ver = "0.2.21" }
, { dep = "uuid-types", ver = "1.0.6" }
, { dep = "vector", ver = "0.13.2.0" }
, { dep = "vector-algorithms", ver = "0.9.1.0" }
, { dep = "vector-stream", ver = "0.1.0.1" }
, { dep = "void", ver = "0.7.4" }
, { dep = "witherable", ver = "0.5" }
]
